### PR TITLE
Switch to mdeditor for reply editor

### LINKED ISSUE #96: Add links to letter replies [6h, time spent: 4h]
Our customers should be able to click on the links in online letters.

### PR DESCRIPTION
**Pull request by andri-yta**
Related to this PR [https://github.com/Naisten-Linja/naisten-linja-public-website/pull/97](https://github.com/Naisten-Linja/naisten-linja-public-website/pull/97)

### CODE REVIEW

**Comment by andri-yta** [comment]
Needs to add sanitation against XSS attacks

**Comment by tuomas-tk** [comment]
Oh just found a new bug, I sent a completely new letter as a customer, and then tried to open the individual letter page as staff. Because there is no reply written yet, it gave me error
```
Reply.tsx:80 TypeError: Cannot read properties of null (reading 'content')
    at Reply.tsx:78:1
```

Preferrably TypeScript should have caught this, I think the type on `Reply.tsx:74` should be modified from `ApiReplyAdmin` to `ApiReplyAdmin | null`

**Comment by andri-yta** [comment]
> Oh just found a new bug, I sent a completely new letter as a customer, and then tried to open the individual letter page as staff. Because there is no reply written yet, it gave me error
> 
> ```
> Reply.tsx:80 TypeError: Cannot read properties of null (reading 'content')
>     at Reply.tsx:78:1
> ```
> 
> Preferrably TypeScript should have caught this, I think the type on `Reply.tsx:74` should be modified from `ApiReplyAdmin` to `ApiReplyAdmin | null`

This `setContent(result.data.data?.content)` would also work too, but is it a good practice?

**Comment by tuomas-tk** [comment]
> > Oh just found a new bug, I sent a completely new letter as a customer, and then tried to open the individual letter page as staff. Because there is no reply written yet, it gave me error
> > ```
> > Reply.tsx:80 TypeError: Cannot read properties of null (reading 'content')
> >     at Reply.tsx:78:1
> > ```
> > Preferrably TypeScript should have caught this, I think the type on `Reply.tsx:74` should be modified from `ApiReplyAdmin` to `ApiReplyAdmin | null`
> 
> This `setContent(result.data.data?.content)` would also work too, but is it a good practice?

Yeah I think that should be fine, that operator is not just TypeScript thing to force types to be different, but it actually works something like `(result.data.data) ? result.data.data.content : undefined`. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

But even then the type on line 74 should be changed, because otherwise TypeScript can think that result.data.data can never be null, which can at least cause type problems in the future, but maybe also it can remove the `?.` operator thinking that it is not needed, which breaks the app again

**Review by tuomas-tk — APPROVED** [review]

**Pull request merged**
